# Q-Table Learning

In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

[2017-07-25 16:21:15,057] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    env.render()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF

In [5]:
print("Score over time: " +  str(sum(rList)/num_episodes) )

Score over time: 0.442


In [7]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.29694919e-01   5.94134709e-03   8.89877515e-03   5.78203480e-03]
 [  2.67409531e-04   1.02034825e-04   1.07970316e-04   1.04911829e-01]
 [  7.96741435e-02   1.27645952e-03   6.00733921e-03   4.71008116e-03]
 [  8.15295785e-04   1.54317711e-04   1.17348149e-04   5.92934881e-03]
 [  9.25369968e-02   5.97507598e-04   9.89963878e-05   5.49721487e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.30742348e-04   3.75746122e-07   5.93362809e-04   1.97864574e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.25414114e-04   7.21859279e-04   1.30983335e-04   4.96100976e-02]
 [  8.04418653e-04   1.04226498e-02   1.72203959e-03   7.17811036e-04]
 [  7.57808764e-02   3.32463072e-04   2.29170187e-03   4.71313766e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.92961449e-04   1.58908254e-04   4.43284217e-01   8